name: Deploy api to Raspberry Pi

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy the app
        run: |
          ssh ${{ secrets.PI_USER }}@${{ secrets.PI_IP_ADDRESS }} << 'EOF'
            cd path/
            git pull origin prod
            pip install -r requirements.txt
            pkill -f "uvicorn"
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          EOF